-- Run this in the SQL editor of the NEW project only.
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  pupil_id text not null,
  pupil_name text not null,
  class_name text not null,
  status text not null check (status in ('present','absent','late')),
  submitted_at timestamptz not null default now()
);

alter table public.attendance enable row level security;

-- MVP/demo policy: authenticated users can read and insert.
-- Tighten this to school/class ownership before any real-world pilot.
create policy "authenticated can read attendance"
on public.attendance
for select
to authenticated
using (true);

create policy "authenticated can insert attendance"
on public.attendance
for insert
to authenticated
with check (true);
